# Generated by Django 6.0.2 on 2026-04-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_method_payment_month_payment_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
    ]
