services:
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      DB_NAME: rent_system_db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:15
    container_name: postgres_db

    environment:
      POSTGRES_DB: rent_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: