# Generated by Django 6.0.2 on 2026-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_created_at_house_total_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
