# Generated by Django 6.0.2 on 2026-04-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_created_at_tenant_property_tenant_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
